# Generated by Django 2.1.3 on 2018-11-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkworld', '0002_auto_20181127_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
