# Generated by Django 2.1.3 on 2018-11-27 06:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('post', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('post', 'voter')},
        ),
    ]
