# Generated by Django 2.1.3 on 2018-11-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181127_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
