# Generated by Django 2.1.3 on 2018-11-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkworld', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.BooleanField(default=False),
        ),
    ]
