# Generated by Django 2.1.3 on 2018-11-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkworld', '0003_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
