# Generated by Django 2.1.3 on 2018-11-29 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkworld', '0004_auto_20181128_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
