# Generated by Django 2.1.3 on 2018-11-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkworld', '0004_auto_20181130_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
